// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using weitus_backend.Data;

#nullable disable

namespace weitus_backend.Migrations
{
    [DbContext(typeof(WeitusDbContext))]
    [Migration("20230108225326_DB Scheme")]
    partial class DBScheme
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("weitus_backend.Data.Models.ChatBot", b =>
                {
                    b.Property<short>("ChatBotId")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5)
                        .HasColumnType("NUMBER(5)")
                        .HasColumnName("bot_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("ChatBotId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("name");

                    b.HasKey("ChatBotId");

                    b.ToTable("CHAT_BOTS", (string)null);

                    b.HasData(
                        new
                        {
                            ChatBotId = (short)1,
                            Name = "Weituś"
                        });
                });

            modelBuilder.Entity("weitus_backend.Data.Models.ChatMessage", b =>
                {
                    b.Property<int>("ChatMessageId")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("chat_message_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatMessageId"), 1L, 1);

                    b.Property<short>("BotId")
                        .HasColumnType("NUMBER(5)")
                        .HasColumnName("bot_id");

                    b.Property<int>("ChatterId")
                        .HasColumnType("NUMBER(8)")
                        .HasColumnName("chatter_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("message");

                    b.Property<bool>("SentByBot")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("sent_by_bot");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("timestamp");

                    b.HasKey("ChatMessageId");

                    b.HasIndex("BotId");

                    b.HasIndex("ChatterId");

                    b.HasIndex("TimeStamp");

                    b.ToTable("CHAT_MESSAGES", (string)null);
                });

            modelBuilder.Entity("weitus_backend.Data.Models.WeitusUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(8)
                        .HasColumnType("NUMBER(8)")
                        .HasColumnName("user_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)")
                        .HasColumnName("password_salt");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.ToTable("USERS", (string)null);
                });

            modelBuilder.Entity("weitus_backend.Data.Models.ChatMessage", b =>
                {
                    b.HasOne("weitus_backend.Data.Models.ChatBot", "Bot")
                        .WithMany("ChatMessages")
                        .HasForeignKey("BotId");

                    b.HasOne("weitus_backend.Data.Models.WeitusUser", "Chatter")
                        .WithMany("ChatMessages")
                        .HasForeignKey("ChatterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bot");

                    b.Navigation("Chatter");
                });

            modelBuilder.Entity("weitus_backend.Data.Models.ChatBot", b =>
                {
                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("weitus_backend.Data.Models.WeitusUser", b =>
                {
                    b.Navigation("ChatMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
